export const data = [
  {
    "S.no": "1",
    "Investor Name": "Alpha Ventures",
    "Fund Type": "Venture Capital",
    "Fund Stage": "Seed",
    Website: "https://alphaventures.com",
    "Fund Focus (Sectors)": "Technology;Healthcare;FinTech",
    "Partner Name": "John Doe",
    "Partner Email": "john@alphaventures.com",
    "Portfolio Companies": "Company A;Company B",
    Location: "New York",
    "Twitter Link": "https://twitter.com/alphaventures",
    "LinkedIn Link": "https://linkedin.com/in/alphaventures",
    "Facebook Link": "https://facebook.com/alphaventures",
    "Number of Investments": "50",
    "Number of Exits": "10",
    "Fund Description":
      "Early-stage venture capital firm focusing on tech and healthcare",
    "Founding Year": "2005",
  },
  {
    "S.no": "2",
    "Investor Name": "Beta Capital",
    "Fund Type": "Private Equity",
    "Fund Stage": "Growth",
    Website: "https://betacapital.com",
    "Fund Focus (Sectors)": "Real Estate;Retail",
    "Partner Name": "Sarah Lee",
    "Partner Email": "sarah@betacapital.com",
    "Portfolio Companies": "Company C;Company D",
    Location: "San Francisco",
    "Twitter Link": "https://twitter.com/betacapital",
    "LinkedIn Link": "https://linkedin.com/in/betacapital",
    "Facebook Link": "https://facebook.com/betacapital",
    "Number of Investments": "75",
    "Number of Exits": "25",
    "Fund Description":
      "Investing in high-growth retail and real estate businesses",
    "Founding Year": "2010",
  },
  {
    "S.no": "3",
    "Investor Name": "Gamma Investments",
    "Fund Type": "Angel",
    "Fund Stage": "Seed",
    Website: "https://gammainvestments.com",
    "Fund Focus (Sectors)": "Clean Energy;Tech",
    "Partner Name": "Michael Tan",
    "Partner Email": "michael@gammainvestments.com",
    "Portfolio Companies": "Company E;Company F",
    Location: "Chicago",
    "Twitter Link": "https://twitter.com/gammainvestments",
    "LinkedIn Link": "https://linkedin.com/in/gammainvestments",
    "Facebook Link": "https://facebook.com/gammainvestments",
    "Number of Investments": "30",
    "Number of Exits": "5",
    "Fund Description": "Angel fund investing in sustainable tech",
    "Founding Year": "2012",
  },
  {
    "S.no": "4",
    "Investor Name": "Delta Partners",
    "Fund Type": "Venture Capital",
    "Fund Stage": "Series A",
    Website: "https://deltapartners.com",
    "Fund Focus (Sectors)": "Healthcare;Education",
    "Partner Name": "Lisa Wong",
    "Partner Email": "lisa@deltapartners.com",
    "Portfolio Companies": "Company G;Company H",
    Location: "Boston",
    "Twitter Link": "https://twitter.com/deltapartners",
    "LinkedIn Link": "https://linkedin.com/in/deltapartners",
    "Facebook Link": "https://facebook.com/deltapartners",
    "Number of Investments": "60",
    "Number of Exits": "15",
    "Fund Description": "Series A focused VC for health and education",
    "Founding Year": "2008",
  },
  {
    "S.no": "5",
    "Investor Name": "Epsilon Ventures",
    "Fund Type": "Venture Capital",
    "Fund Stage": "Series B",
    Website: "https://epsilonventures.com",
    "Fund Focus (Sectors)": "Finance;Blockchain",
    "Partner Name": "Richard Li",
    "Partner Email": "richard@epsilonventures.com",
    "Portfolio Companies": "Company I;Company J",
    Location: "Seattle",
    "Twitter Link": "https://twitter.com/epsilonventures",
    "LinkedIn Link": "https://linkedin.com/in/epsilonventures",
    "Facebook Link": "https://facebook.com/epsilonventures",
    "Number of Investments": "85",
    "Number of Exits": "30",
    "Fund Description": "Blockchain and finance-focused venture capital",
    "Founding Year": "2009",
  },
  {
    "S.no": "6",
    "Investor Name": "Zeta Group",
    "Fund Type": "Private Equity",
    "Fund Stage": "Late Stage",
    Website: "https://zetagroup.com",
    "Fund Focus (Sectors)": "Logistics;Manufacturing",
    "Partner Name": "Tom Green",
    "Partner Email": "tom@zetagroup.com",
    "Portfolio Companies": "Company K;Company L",
    Location: "Austin",
    "Twitter Link": "https://twitter.com/zetagroup",
    "LinkedIn Link": "https://linkedin.com/in/zetagroup",
    "Facebook Link": "https://facebook.com/zetagroup",
    "Number of Investments": "90",
    "Number of Exits": "35",
    "Fund Description": "Investing in late-stage logistics and manufacturing",
    "Founding Year": "2007",
  },
  {
    "S.no": "7",
    "Investor Name": "Eta Capital",
    "Fund Type": "Angel",
    "Fund Stage": "Pre-Seed",
    Website: "https://etacapital.com",
    "Fund Focus (Sectors)": "Consumer Goods;FinTech",
    "Partner Name": "Nancy Chen",
    "Partner Email": "nancy@etacapital.com",
    "Portfolio Companies": "Company M;Company N",
    Location: "Miami",
    "Twitter Link": "https://twitter.com/etacapital",
    "LinkedIn Link": "https://linkedin.com/in/etacapital",
    "Facebook Link": "https://facebook.com/etacapital",
    "Number of Investments": "20",
    "Number of Exits": "2",
    "Fund Description": "Pre-seed fund for consumer goods startups",
    "Founding Year": "2013",
  },
  {
    "S.no": "8",
    "Investor Name": "Theta Ventures",
    "Fund Type": "Venture Capital",
    "Fund Stage": "Seed",
    Website: "https://thetaventures.com",
    "Fund Focus (Sectors)": "Agriculture;AI",
    "Partner Name": "Peter Zhang",
    "Partner Email": "peter@thetaventures.com",
    "Portfolio Companies": "Company O;Company P",
    Location: "Dallas",
    "Twitter Link": "https://twitter.com/thetaventures",
    "LinkedIn Link": "https://linkedin.com/in/thetaventures",
    "Facebook Link": "https://facebook.com/thetaventures",
    "Number of Investments": "40",
    "Number of Exits": "8",
    "Fund Description": "Seed-stage VC specializing in agriculture tech",
    "Founding Year": "2011",
  },
  {
    "S.no": "9",
    "Investor Name": "Iota Partners",
    "Fund Type": "Private Equity",
    "Fund Stage": "Growth",
    Website: "https://iotapartners.com",
    "Fund Focus (Sectors)": "Education;SaaS",
    "Partner Name": "Alex Kim",
    "Partner Email": "alex@iotapartners.com",
    "Portfolio Companies": "Company Q;Company R",
    Location: "Denver",
    "Twitter Link": "https://twitter.com/iotapartners",
    "LinkedIn Link": "https://linkedin.com/in/iotapartners",
    "Facebook Link": "https://facebook.com/iotapartners",
    "Number of Investments": "65",
    "Number of Exits": "20",
    "Fund Description": "Focused on SaaS and education tech growth",
    "Founding Year": "2014",
  },
  {
    "S.no": "10",
    "Investor Name": "Kappa Investments",
    "Fund Type": "Angel",
    "Fund Stage": "Series A",
    Website: "https://kappainvestments.com",
    "Fund Focus (Sectors)": "Energy;Green Tech",
    "Partner Name": "Emma Lee",
    "Partner Email": "emma@kappainvestments.com",
    "Portfolio Companies": "Company S;Company T",
    Location: "Las Vegas",
    "Twitter Link": "https://twitter.com/kappainvestments",
    "LinkedIn Link": "https://linkedin.com/in/kappainvestments",
    "Facebook Link": "https://facebook.com/kappainvestments",
    "Number of Investments": "55",
    "Number of Exits": "12",
    "Fund Description": "Angel fund for green energy and tech",
    "Founding Year": "2015",
  },
  {
    "S.no": "11",
    "Investor Name": "Lambda Ventures",
    "Fund Type": "Venture Capital",
    "Fund Stage": "Seed",
    Website: "https://lambdaventures.com",
    "Fund Focus (Sectors)": "MedTech;AI",
    "Partner Name": "Jake Wilson",
    "Partner Email": "jake@lambdaventures.com",
    "Portfolio Companies": "Company U;Company V",
    Location: "Houston",
    "Twitter Link": "https://twitter.com/lambdaventures",
    "LinkedIn Link": "https://linkedin.com/in/lambdaventures",
    "Facebook Link": "https://facebook.com/lambdaventures",
    "Number of Investments": "70",
    "Number of Exits": "18",
    "Fund Description": "Early-stage medtech and AI",
    "Founding Year": "2016",
  },
  {
    "S.no": "12",
    "Investor Name": "Mu Capital",
    "Fund Type": "Private Equity",
    "Fund Stage": "Late Stage",
    Website: "https://mucapital.com",
    "Fund Focus (Sectors)": "Clean Energy;Infrastructure",
    "Partner Name": "Alice Wong",
    "Partner Email": "alice@mucapital.com",
    "Portfolio Companies": "Company W;Company X",
    Location: "Phoenix",
    "Twitter Link": "https://twitter.com/mucapital",
    "LinkedIn Link": "https://linkedin.com/in/mucapital",
    "Facebook Link": "https://facebook.com/mucapital",
    "Number of Investments": "80",
    "Number of Exits": "25",
    "Fund Description": "Focused on sustainable infrastructure",
    "Founding Year": "2006",
  },
  {
    "S.no": "13",
    "Investor Name": "Nu Investments",
    "Fund Type": "Angel",
    "Fund Stage": "Seed",
    Website: "https://nuinvestments.com",
    "Fund Focus (Sectors)": "AgriTech;Biotech",
    "Partner Name": "Leo Chen",
    "Partner Email": "leo@nuinvestments.com",
    "Portfolio Companies": "Company Y;Company Z",
    Location: "Orlando",
    "Twitter Link": "https://twitter.com/nuinvestments",
    "LinkedIn Link": "https://linkedin.com/in/nuinvestments",
    "Facebook Link": "https://facebook.com/nuinvestments",
    "Number of Investments": "35",
    "Number of Exits": "10",
    "Fund Description": "Agri-tech angel investments",
    "Founding Year": "2017",
  },
  {
    "S.no": "14",
    "Investor Name": "Xi Partners",
    "Fund Type": "Venture Capital",
    "Fund Stage": "Series B",
    Website: "https://xipartners.com",
    "Fund Focus (Sectors)": "Finance;Healthcare",
    "Partner Name": "Betty Brown",
    "Partner Email": "betty@xipartners.com",
    "Portfolio Companies": "Company AA;Company BB",
    Location: "San Diego",
    "Twitter Link": "https://twitter.com/xipartners",
    "LinkedIn Link": "https://linkedin.com/in/xipartners",
    "Facebook Link": "https://facebook.com/xipartners",
    "Number of Investments": "95",
    "Number of Exits": "40",
    "Fund Description": "Series B investments in finance",
    "Founding Year": "2003",
  },
  {
    "S.no": "15",
    "Investor Name": "Omicron Ventures",
    "Fund Type": "Venture Capital",
    "Fund Stage": "Series A",
    Website: "https://omicronventures.com",
    "Fund Focus (Sectors)": "Clean Tech;AI",
    "Partner Name": "Sam White",
    "Partner Email": "sam@omicronventures.com",
    "Portfolio Companies": "Company CC;Company DD",
    Location: "Detroit",
    "Twitter Link": "https://twitter.com/omicronventures",
    "LinkedIn Link": "https://linkedin.com/in/omicronventures",
    "Facebook Link": "https://facebook.com/omicronventures",
    "Number of Investments": "75",
    "Number of Exits": "20",
    "Fund Description": "Green technology and AI investment",
    "Founding Year": "2018",
  },
  {
    "S.no": "16",
    "Investor Name": "Phi Capital",
    "Fund Type": "Private Equity",
    "Fund Stage": "Growth",
    Website: "https://phicapital.com",
    "Fund Focus (Sectors)": "Real Estate;HealthTech",
    "Partner Name": "Linda Grey",
    "Partner Email": "linda@phicapital.com",
    "Portfolio Companies": "Company EE;Company FF",
    Location: "Nashville",
    "Twitter Link": "https://twitter.com/phicapital",
    "LinkedIn Link": "https://linkedin.com/in/phicapital",
    "Facebook Link": "https://facebook.com/phicapital",
    "Number of Investments": "100",
    "Number of Exits": "45",
    "Fund Description": "Investing in health tech growth",
    "Founding Year": "2011",
  },
  {
    "S.no": "17",
    "Investor Name": "Chi Investments",
    "Fund Type": "Angel",
    "Fund Stage": "Pre-Seed",
    Website: "https://chiinvestments.com",
    "Fund Focus (Sectors)": "Entertainment;Gaming",
    "Partner Name": "Brian Black",
    "Partner Email": "brian@chiinvestments.com",
    "Portfolio Companies": "Company GG;Company HH",
    Location: "Portland",
    "Twitter Link": "https://twitter.com/chiinvestments",
    "LinkedIn Link": "https://linkedin.com/in/chiinvestments",
    "Facebook Link": "https://facebook.com/chiinvestments",
    "Number of Investments": "25",
    "Number of Exits": "3",
    "Fund Description": "Pre-seed fund for gaming startups",
    "Founding Year": "2019",
  },
  {
    "S.no": "18",
    "Investor Name": "Psi Partners",
    "Fund Type": "Venture Capital",
    "Fund Stage": "Seed",
    Website: "https://psipartners.com",
    "Fund Focus (Sectors)": "Consumer Tech;Retail",
    "Partner Name": "David Ross",
    "Partner Email": "david@psipartners.com",
    "Portfolio Companies": "Company II;Company JJ",
    Location: "Atlanta",
    "Twitter Link": "https://twitter.com/psipartners",
    "LinkedIn Link": "https://linkedin.com/in/psipartners",
    "Facebook Link": "https://facebook.com/psipartners",
    "Number of Investments": "65",
    "Number of Exits": "12",
    "Fund Description": "Consumer tech investments",
    "Founding Year": "2007",
  },
  {
    "S.no": "19",
    "Investor Name": "Omega Group",
    "Fund Type": "Private Equity",
    "Fund Stage": "Late Stage",
    Website: "https://omegagroup.com",
    "Fund Focus (Sectors)": "Biotech;FinTech",
    "Partner Name": "Rachel Li",
    "Partner Email": "rachel@omegagroup.com",
    "Portfolio Companies": "Company KK;Company LL",
    Location: "Minneapolis",
    "Twitter Link": "https://twitter.com/omegagroup",
    "LinkedIn Link": "https://linkedin.com/in/omegagroup",
    "Facebook Link": "https://facebook.com/omegagroup",
    "Number of Investments": "105",
    "Number of Exits": "50",
    "Fund Description": "Biotech-focused private equity",
    "Founding Year": "2000",
  },
  {
    "S.no": "20",
    "Investor Name": "Sigma Ventures",
    "Fund Type": "Venture Capital",
    "Fund Stage": "Series B",
    Website: "https://sigmaventures.com",
    "Fund Focus (Sectors)": "Renewable Energy;Tech",
    "Partner Name": "Victor Grey",
    "Partner Email": "victor@sigmaventures.com",
    "Portfolio Companies": "Company MM;Company NN",
    Location: "Salt Lake City",
    "Twitter Link": "https://twitter.com/sigmaventures",
    "LinkedIn Link": "https://linkedin.com/in/sigmaventures",
    "Facebook Link": "https://facebook.com/sigmaventures",
    "Number of Investments": "90",
    "Number of Exits": "22",
    "Fund Description": "Supporting renewable energy ventures",
    "Founding Year": "2004",
  },
  {
    "S.no": "21",
    "Investor Name": "Upsilon Investments",
    "Fund Type": "Angel",
    "Fund Stage": "Seed",
    Website: "https://upsiloninvestments.com",
    "Fund Focus (Sectors)": "EdTech;Digital Media",
    "Partner Name": "Olivia Green",
    "Partner Email": "olivia@upsiloninvestments.com",
    "Portfolio Companies": "Company OO;Company PP",
    Location: "Baltimore",
    "Twitter Link": "https://twitter.com/upsiloninvestments",
    "LinkedIn Link": "https://linkedin.com/in/upsiloninvestments",
    "Facebook Link": "https://facebook.com/upsiloninvestments",
    "Number of Investments": "30",
    "Number of Exits": "7",
    "Fund Description": "Angel fund for digital media and edtech",
    "Founding Year": "2015",
  },
  {
    "S.no": "22",
    "Investor Name": "Phi Ventures",
    "Fund Type": "Venture Capital",
    "Fund Stage": "Seed",
    Website: "https://phiventures.com",
    "Fund Focus (Sectors)": "Healthcare;Food Tech",
    "Partner Name": "Ethan Yang",
    "Partner Email": "ethan@phiventures.com",
    "Portfolio Companies": "Company QQ;Company RR",
    Location: "Cleveland",
    "Twitter Link": "https://twitter.com/phiventures",
    "LinkedIn Link": "https://linkedin.com/in/phiventures",
    "Facebook Link": "https://facebook.com/phiventures",
    "Number of Investments": "55",
    "Number of Exits": "10",
    "Fund Description": "Seed-stage investments in food tech",
    "Founding Year": "2001",
  },
  {
    "S.no": "23",
    "Investor Name": "Omega Partners",
    "Fund Type": "Private Equity",
    "Fund Stage": "Late Stage",
    Website: "https://omegapartners.com",
    "Fund Focus (Sectors)": "Clean Tech;Water Tech",
    "Partner Name": "Julia White",
    "Partner Email": "julia@omegapartners.com",
    "Portfolio Companies": "Company SS;Company TT",
    Location: "San Antonio",
    "Twitter Link": "https://twitter.com/omegapartners",
    "LinkedIn Link": "https://linkedin.com/in/omegapartners",
    "Facebook Link": "https://facebook.com/omegapartners",
    "Number of Investments": "110",
    "Number of Exits": "47",
    "Fund Description": "Investing in water and clean tech",
    "Founding Year": "2002",
  },
  {
    "S.no": "24",
    "Investor Name": "Phi Capital Partners",
    "Fund Type": "Angel",
    "Fund Stage": "Pre-Seed",
    Website: "https://phicapitalpartners.com",
    "Fund Focus (Sectors)": "HealthTech;E-commerce",
    "Partner Name": "Robert Park",
    "Partner Email": "robert@phicapitalpartners.com",
    "Portfolio Companies": "Company UU;Company VV",
    Location: "Oklahoma City",
    "Twitter Link": "https://twitter.com/phicapitalpartners",
    "LinkedIn Link": "https://linkedin.com/in/phicapitalpartners",
    "Facebook Link": "https://facebook.com/phicapitalpartners",
    "Number of Investments": "25",
    "Number of Exits": "5",
    "Fund Description": "Angel investments in e-commerce and health tech",
    "Founding Year": "2021",
  },
  {
    "S.no": "25",
    "Investor Name": "Alpha Group",
    "Fund Type": "Venture Capital",
    "Fund Stage": "Series A",
    Website: "https://alphagroup.com",
    "Fund Focus (Sectors)": "Tech;Finance",
    "Partner Name": "Susan James",
    "Partner Email": "susan@alphagroup.com",
    "Portfolio Companies": "Company WW;Company XX",
    Location: "Columbus",
    "Twitter Link": "https://twitter.com/alphagroup",
    "LinkedIn Link": "https://linkedin.com/in/alphagroup",
    "Facebook Link": "https://facebook.com/alphagroup",
    "Number of Investments": "80",
    "Number of Exits": "18",
    "Fund Description": "Series A fund in tech and finance",
    "Founding Year": "2010",
  },
];
